##
## Makefile for Makefile in /home/lopez_i/cpp_arcade
##
## Made by Loic Lopez
## Login   <loic.lopez@epitech.eu>
##
## Started on  Mon Mar  6 09:53:13 2017 Loic Lopez
## Last update Mon Mar  6 10:31:07 2017 Loic Lopez
##

all:
	@make --no-print-directory -C Snake
	@make --no-print-directory -C SpaceFighter

clean:
	@make clean  --no-print-directory -C Snake
	@make clean  --no-print-directory -C SpaceFighter

fclean:
	@make fclean  --no-print-directory -C Snake
	@make fclean  --no-print-directory -C SpaceFighter

re:
	@make re  --no-print-directory -C Snake
	@make re  --no-print-directory -C SpaceFighter